# Generated by Django 3.2.6 on 2021-08-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='icon',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
