# Generated by Django 3.2.6 on 2021-09-01 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_item_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='shippingAddress',
        ),
    ]
