# Generated by Django 3.2.6 on 2021-09-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_customeruser_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='shippingAddress',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
