# Generated by Django 3.2.6 on 2021-09-02 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_contactus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='message',
        ),
        migrations.RemoveField(
            model_name='contactus',
            name='subject',
        ),
    ]
